
# Template workflow for the OpenShift GitHub Connector

name: OpenShift
on:
  push:
    branches: [ "n/a" ]

permissions: {}

jobs:
  openshift:
    name: OpenShift
    runs-on: ubuntu-20.04
    permissions:
      contents: read

    steps:
      - name: Install OpenShift Client
        uses: redhat-actions/openshift-tools-installer@144527c7d98999f2652264c048c7a9bd103f8a82 # v1
        with:
          oc: 4

      - name: Login to OpenShift
        uses: redhat-actions/oc-login@5eb45e848b168b6bf6b8fe7f1561003c12e3c99d # v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}

      - name: Test
        run: oc get po

      # You can now work with this OpenShift cluster for the rest of the job.
